server:
  port: 8081
  servlet:
    context-path: /api/backend
spring:
  profiles:
    active: dev
  application:
    name: service-backend
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: localhost:8848
        username: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 137911
    url: jdbc:mysql://localhost:3306/openapi
  session:
    store-type: redis
    timeout: 86400
  redis:
    host: localhost
    port: 6379
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
dubbo:
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
