server:
  port: 8000

spring:
  session:
    store-type: redis
    timeout: 86400
  redis:
    host: localhost
    port: 6379
    database: 0
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      enabled: true
      routes:
        - id: service-backend
          uri: lb://service-backend
          predicates:
            - Path=/api/backend/**
        - id: service-manager
          uri: lb://service-manager
          predicates:
            - Path=/api/manager/**

dubbo:
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace